### ISSUE TITLE
Ghost processes

### ISSUE THREAD

**Issue by mellson** [zth/vscode-rescript-relay#3]
Opening this issue so we have a place to talk about the current situtation where sometimes the plugin leaves a lot of ghost processes around. Currently I'm seeing node and watchman processes left running even after i quit code.

**Comment by zth** [comment]
Yeah, this is a major pain and needs to be fixed! I've attempted to fix it a few times, but never fully nailing it. It'd be good to start by investigating exactly when it happens. We'll need to do some proper digging, but one suspicious thing is when you reload the full VSCode window via the reload command.

**Comment by zth** [comment]
Fixed and released https://github.com/zth/vscode-rescript-relay/commit/a6bc192a8d8f40511e7c2327c5cea21e1803cfac
