### ISSUE TITLE
Move away from `vscode` to `@types/vscode`

### ISSUE THREAD

**Issue by filiptronicek** [zth/vscode-rescript-relay#31]
The [`vscode` package on NPM](https://www.npmjs.com/package/vscode) has been deprecated in favor of [`@types/vscode`](https://www.npmjs.com/package/@types/vscode). As it might cause some issues in the future, it would be awesome to address it.

**Comment by zth** [comment]
Fixed in https://github.com/zth/vscode-rescript-relay/commit/d0a111e1928f37e34f1e96b1958ac848fa3ece03
